name: Library Release Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GITHUB_USERNAME: "demndevel"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY_CONTENTS }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}

jobs:

  test-jvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache Setup
        uses: gradle/gradle-build-action@v2.4.2
      - name: Gradle Check
        run: ./gradlew jvmTest

  deploy-jvm:
    runs-on: ubuntu-latest
    needs:
      - test-jvm
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache Setup
        uses: gradle/gradle-build-action@v2.4.2
      - name: Gradle Sync
        run: ./gradlew
      - name: Add Sdk Version to Env
        run: |
          release_version=$(./gradlew printVersion -q)
          echo "release_version=$release_version" >> $GITHUB_ENV
      - name: Publish ${{ env.release_version }}
        run: ./gradlew publishJvmPublicationToMavenCentralRepository

  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - deploy-jvm

    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.deploy-multiplatform.outputs.release_version }}
          name: Release ${{ needs.deploy-multiplatform.outputs.release_version }}